### PR TITLE
Refactored businesss_list->businesses and deploy_loc_list->deploy_loc…

### PR DESCRIPTION
**Pull request by wolfpack94**
Issue #48 Refactored business_list to businesses and deploy_loc_list to deploy_locations.
Tested and verified the code still works with the changes.

### CODE REVIEW

**Comment by wolfpack94** [comment]
alright fixed the conflicts. Thank you for checking.

**Comment by j0j0r0** [comment]
Reviewing, just saw this is still open. 
Looks like it's out of date or changes were already merged? 
Please verify @wolfpack94

**Comment by wolfpack94** [comment]
This has already been merged. Checked through master branch.

**Comment by j0j0r0** [comment]
Ok. Thank you.

**Pull request closed without merging**
