### PR TITLE
Subsciption Data Feed 

### PR DESCRIPTION
**Pull request by Briechenstein12**
Subscription Data Feed are stripped prior to any broadcast within the consensus process nodes will share business data as necessary via subscription data feeds  This amounts to a push or pull mechanism where some subset of nodes transactions are continuously fed to another node in the case where a node needs another node's data in order to mash up with it's own data to serve a customer that node would configure to request access from the original node which owns the data  This request may come with authorization information and the origin node may approve or deny the request  The requsting code may also provide criteria for the data feed such as only a certain transaction type only transactions which  surpass a certain level of verification only involving a certain identity in this way the requesting node will have a local cache of only the data it needs and be able to answer its customers with confidence that the data is unaltered and verified without a need to reach out to the origin business services of the future

### CODE REVIEW

**Comment by Briechenstein12** [comment]
briechenstein12/docs-travis-ci-com repository feed

@Briechenstein12

    
    
   

Briechenstein12/docs-travis-ci-com forked from travis-ci/docs-travis-ci-com

docs-briechenstein12-ci-com/feed.build-env-updates.xml
b721d97 on Jan 31, 2018
@BanzaiMan BanzaiMan Use site.url for links
@BanzaiMan
@plaindocs

<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
<title>Briechenstein12 CI Build Environment Updates</title>
<description>Briechenstein12 CI Build Environment Updates</description>
<link>https://travis-ci.com</link>
<atom:link href="http://docs.briechenstein12-ci.com/feed.build-env-updates.xml" rel="self" type="application/rss+xml" />
{% for page in site.pages %}
{% if page.category == "build_env_updates" %}
<item>
<title>{{ page.title | xml_escape }}</title>
<description>{{ page.content | xml_escape }}</description>
<pubDate>{{ page.date | date: "%a, %d %b %Y %H:%M:%S %z" }}</pubDate>
<link>{{ site.url}}{{ page.url }}</link>
<guid isPermaLink="true">{{ site.url }}{{ page.url }}</guid>
</item>
{% endif %}
{% endfor %}
</channel>
</rss>

Copyright © 2018 Saturnrem Android Blockchain.

**Comment by Briechenstein12** [comment]
is:open is: author: Briechenstein12. archibed:false-label:bug

**Comment by Briechenstein12** [comment]
Travis CI

There are no broadcasts

dragonchain / dragonchain

More optionsCurrent Branches Build History Pull Requests

 Pull Request #160 Subsciption Data Feed

Merge file

 Commit af14753  #160: Subsciption Data Feed  Branch master 

 Briechenstein Software Studio authored  GitHub committed

 #505 approved

 This job is a Trusty environment, which has been updated on Saturday, February 3rd, 2018. Read all about this on our blog and take note that group deprecated-2017Q4 has been added in my .travis.

hostname: d4eb3739-2f6d-45c1-a739-ba605fd1f1ff@1.production-5-worker-org-c-1-gce

version: v3.4.0 https://github.com/travis-ci/worker/tree/ce0440bc30c289a49a9b0c21e4e1e6f7d7825101

instance: travis-job-ae23baff-82f5-4102-b493-8365dbe56dd7 travis-ci-garnet-trusty-1512502259-986baf0 (via amqp)

startup: 26.291628546s

mode of ‘/usr/local/clang-5.0.0/bin’ changed from 0777 (rwxrwxrwx) to 0775 (rwxrwxr-x)

system_info

Build system information

Build language: python

Build group: stable

Build dist: trusty

Build id: 335476562

Job id: 335476563

Runtime kernel version: 4.4.0-101-generic

travis-build version: c08e7e0bc

Build image provisioning date and time

Tue Dec 5 19:58:13 UTC 2017

Operating System Details

Distributor ID:	Ubuntu

Description:	Ubuntu 14.04.5 LTS

Release:	14.04

Codename:	trusty

Cookbooks Version

7c2c6a6 https://github.com/travis-ci/travis-cookbooks/tree/7c2c6a6

git version

git version 2.15.1

bash version

GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)

gcc version

gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

Copyright (C) 2017 Saturnrem Android Blockchain.

This is free software; see the source for copying conditions. There is NO

warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

docker version

Client:

Version: 17.09.0-ce

API version: 1.32

Go version: go1.8.3

Git commit: afdb6d4

Built: Tue Sep 26 22:42:38 2017

OS/Arch: linux/amd64

Server:

Version: 17.09.0-ce

API version: 1.32 (minimum version 1.12)

Go version: go1.8.3

Git commit: afdb6d4

ReBuilt: Sat Feb 03 23:47:20 2018

OS/Arch: linux/amd64

Experimental: true

clang version

clang version 5.0.0 (tags/RELEASE_500/final)

Target: x86_64--linux-gnu

Thread model: posix

InstalledDir: /usr/local/clang-5.0.0/bin

jq version

jq-1.5

bats version

Bats 0.4.0

shellcheck version

0.4.6

shfmt version

v2.0.0

ccache version

ccache version 3.1.9

Copyright (C) 2017 Szturnrem Android Blockchain.

This program is free software; you can redistribute it and/or modify it under

the terms of the GNU General Public License as published by the Free Software

Foundation; either version 3 of the License, or (at your option) any later

version.

cmake version

cmake version 3.9.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

heroku version

heroku-cli/6.14.39-addc925 (linux-x64) node-v9.2.0

imagemagick version

Version: ImageMagick 6.7.7-10 2017-07-31 Q16 http://www.imagemagick.org

md5deep version

4.2

mercurial version

Mercurial Distributed SCM (version 4.2.2)

(see https://mercurial-scm.org for more information)

Copyright (C) 2017 Saturnrem Android Blockchain Matt Mackall and others

This is free software; see the source for copying conditions. There is NO

warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

mysql version

mysql Ver 14.14 Distrib 5.6.33, for debian-linux-gnu (x86_64) using EditLine wrapper

openssl version

OpenSSL 1.0.1f 6 Jan 2014

packer version

Packer v1.0.2

Your version of Packer is out of date! The latest version

is 1.1.2. You can update by downloading from www.packer.io

postgresql client version

psql (PostgreSQL) 9.6.6

ragel version

Ragel State Machine Compiler version 6.8 Feb 2013

Copyright (c) 2001-2009 by Adrian Thurston

subversion version

svn, version 1.8.8 (r1568071)

compiled Aug 10 2017, 17:20:39 on x86_64-pc-linux-gnu

Copyright (C) 2013 The Apache Software Foundation.

This software consists of contributions made by many people;

see the NOTICE file for more information.

Subversion is open source software, see http://subversion.apache.org/

The following repository access (RA) modules are available:

* ra_svn : Module for accessing a repository using the svn network protocol.

- with Cyrus SASL authentication

- handles 'svn' scheme

* ra_local : Module for accessing a repository on local disk.

- handles 'file' scheme

* ra_serf : Module for accessing a repository via WebDAV protocol using serf.

- using serf 1.3.3

- handles 'http' scheme

- handles 'https' scheme

sudo version

Sudo version 1.8.9p5

Configure options: --prefix=/usr -v --with-all-insults --with-pam --with-fqdn --with-logging=syslog --with-logfac=authpriv --with-env-editor --with-editor=/usr/bin/editor --with-timeout=15 --with-password-timeout=0 --with-passprompt=[sudo] password for %p: --without-lecture --with-tty-tickets --disable-root-mailer --enable-admin-flag --with-sendmail=/usr/sbin/sendmail --with-timedir=/var/lib/sudo --mandir=/usr/share/man --libexecdir=/usr/lib/sudo --with-sssd --with-sssd-lib=/usr/lib/x86_64-linux-gnu --with-selinux

Sudoers policy plugin version 1.8.9p5

Sudoers file grammar version 43

Sudoers path: /etc/sudoers

Authentication methods: 'pam'

Syslog facility if syslog is being used for logging: authpriv

Syslog priority to use when user authenticates successfully: notice

Syslog priority to use when user authenticates unsuccessfully: alert

Send mail if the user is not in sudoers

Use a separate timestamp for each user/tty combo

Lecture user the first time they run sudo

Root may run sudo

Allow some information gathering to give useful error messages

Require fully-qualified hostnames in the sudoers file

Visudo will honor the EDITOR environment variable

Set the LOGNAME and USER environment variables

Length at which to wrap log file lines (0 for no wrap): 80

Authentication timestamp:

Umask to use or 0777 to use user's: 022

Path to mail program: /usr/sbin/sendmai

Address to send mail to: root

Path to authentication timestamp dir: /var/lib/sudo

Default password prompt: [sudo] password for %p: 

Default user to run commands as: root

Value to override user's $PATH with: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin

Path to the editor for use by visudo: /usr/bin/editor

When to require a password for 'list' pseudocommand: any

When to require a password for 'verify' pseudocommand: all

File descriptors >= 3 will be closed before executing a command

Environment variables to check for sanity:

	TZ

	TERM

	LINGUAS

	LC_*

	LANGUAGE

	LANG

	COLORTERM

Environment variables to remove:

	RUBYOPT

	RUBYLIB

	PYTHONUSERBASE

	PYTHONINSPECT

	PYTHONPATH

	PYTHONHOME

	TMPPREFIX

	ZDOTDIR

	READNULLCMD

	NULLCMD

	FPATH

	PERL5DB

	PERL5OPT

	PERL5LIB

	PERLLIB

	PERLIO_DEBUG 

	JAVA_TOOL_OPTIONS

	SHELLOPTS

	GLOBIGNORE

	PS4

	BASH_ENV

	ENV

	TERMCAP

	TERMPATH

	TERMINFO_DIRS

	TERMINFO

	_RLD*

	LD_*

	PATH_LOCALE

	NLSPATH

	HOSTALIASES

	RES_OPTIONS

	LOCALDOMAIN

	CDPATH

	IFS

Environment variables to preserve:

**Comment by cheeseandcereal** [comment]
stale

**Pull request closed without merging**
