### PR TITLE
Issue 22/unit test framework

### PR DESCRIPTION
**Pull request by micylt**
issue #22 

Initial implementation of unit tests for all functions in cryto.py.
DISCLAIMER: Using mock data such as private and public keys for testing purposes only.

Updated travis configuration to run unit tests on builds.

### CODE REVIEW

**Comment by Voxelot** [comment]
Kind of nitpicky, but most python projects use a directory named `/tests` instead `/unit_tests`. Also might not be a bad idea to include a README.md in the tests directory with instructions for running the tests.

**Comment by wolfpack94** [comment]
Changed the folder from unit_tests to tests/. Also added the how to in the README.md

**Comment by wolfpack94** [comment]
travis-ci fails. Trying to figure out configurations for it at the moment. However, the tests can still be run properly like stated in the README.md file.

**Comment by j0j0r0** [comment]
Is the travis-ci failing on build or in the new tests?

**Comment by wolfpack94** [comment]
travis passed on one version but failed on the others. So I am thinking it might be changes in pyunit between versions.

**Comment by micylt** [comment]
Conflicts resolved and ready to merge.

**Comment by j0j0r0** [comment]
Thank you.

**Pull request merged**
