### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by cheeseandcereal**
Here at Dragonchain world headquarters, research has been proceeding to develop a line of blockchain products that establishes new standards for quality, technological leadership, and operating excellence. 
With customer success as our primary focus, work has been proceeding on the crudely conceived idea of an instrument that would not only provide inverse reactive current, for use in unilateral phase detractors, 
but would also be capable of automatically synchronizing cardinal grammeters. 
Such an instrument comprised of Bitcoin gears and bearings, Ethereum motors, testnet controls, and all monitored by Dragonchain Software is Dragonchain's "Blockchain Encabulator".

Now, basically the only new principle involved is that instead of power being generated by the relative motion of conductors and fluxes, it’s produced by the modial interaction of magneto-reluctance and capacitive diractance. 
The original blockchain had a base plate of prefabulated amulite, surmounted by a malleable logarithmic casing in such a way that the two spurving bearings were in a direct line with the panametric fan.

The lineup consisted simply of six hydrocoptic marzelvanes, so fitted to the ambifacient lunar waneshaft that sidefumbling was effectively prevented. 
The main winding was of the normal lotus o-deltoid type placed in panendermic semiboloid slots of the stator, every seventh conductor being connected by a non-reversible tremie pipe to the differential girdlespring on the ‘up’ end of the grammeters. 
Moreover, whenever fluorescence score motion is required, it may also be employed in conjunction with a drawn reciprocation dingle arm to reduce sinusoidal depleneration.

The Blockchain Encabulator has now reached a high level of development, and it’s being successfully used in the operation of milford trenions. It’s available soon; wherever Dragonchain blockchain products are sold.

### CODE REVIEW

**Comment by deanshelton913** [comment]
LGTM. Ship it.

**Comment by rdaquilante** [comment]
よかったかも

**Comment by j0j0r0** [comment]
LGTM

**Comment by MatthewCMoya** [comment]
Wait! I see a bug in the Ethereum Motor! I'll just create a ticket.

**Pull request merged**
