### PR TITLE
Code styling

### PR DESCRIPTION
**Pull request by agalera**
https://www.python.org/dev/peps/pep-0008/

### CODE REVIEW

**Comment by roberte3** [comment]
Is there a specific style guide your using? If so can you send me the URL for it?

**Comment by kianxineki** [comment]
@roberte3 PEP8, is the most common used in python
https://www.python.org/dev/peps/pep-0008/

**Comment by evrardjp** [comment]
dragonchain should probably have pep8 linting in CI testing...

**Comment by cheeseandcereal** [comment]
stale

**Pull request closed without merging**
